### ISSUE TITLE
Why src_mask = single_eval_pos + len(style_src)?

### ISSUE THREAD

**Issue by hedongyan** [PriorLabs/TabPFN#67]
Hello, I want to known why you add a int and a function? There is a TypeError: unsupported operand type(s) for +: 'function' and 'int'.

The position is line 120 in tabpfn/transformer.py

**Comment by noahho** [comment]
The code concerning the style_src should not be needed, I am not sure in which context you encounter the error, but you could likely remove code connected to the style_src
